window.MEMMAN_TRACE = {"program":"MemManBook","version":1,"events":[
  {"seq":0,"type":"section","title":"Arena","text":"A 256-byte bump allocator used as per-turn scratch memory for spells."},
  {"seq":1,"type":"arena_create","arena":"spells","cap":256},
  {"seq":2,"type":"note","text":"Turn 1: allocations are placed back to back; the bump pointer only moves forward."},
  {"seq":3,"type":"arena_alloc","arena":"spells","offset":0,"pad":0,"size":40,"align":8,"top":40,"kind":"Spell","label":"Fire Ball"},
  {"seq":4,"type":"log","text":"Casting Fire Ball"},
  {"seq":5,"type":"arena_alloc","arena":"spells","offset":40,"pad":0,"size":4,"align":4,"top":44,"kind":"DamageRoll","label":"12"},
  {"seq":6,"type":"log","text":"Fire Ball rolls 12 damage"},
  {"seq":7,"type":"note","text":"Spell needs 8-byte alignment, so the arena pads 4 bytes after the 4-byte DamageRoll."},
  {"seq":8,"type":"arena_alloc","arena":"spells","offset":48,"pad":4,"size":40,"align":8,"top":88,"kind":"Spell","label":"Frost Bolt"},
  {"seq":9,"type":"log","text":"Casting Frost Bolt"},
  {"seq":10,"type":"note","text":"End of turn: reset() runs destructors in reverse order and rewinds the pointer to 0."},
  {"seq":11,"type":"arena_reset_begin","arena":"spells","objects":3},
  {"seq":12,"type":"arena_reset","arena":"spells"},
  {"seq":13,"type":"note","text":"Turn 2: cast until the arena is full. create() returns nullptr instead of overflowing."},
  {"seq":14,"type":"arena_alloc","arena":"spells","offset":0,"pad":0,"size":40,"align":8,"top":40,"kind":"Spell","label":"Lightning"},
  {"seq":15,"type":"log","text":"Casting Lightning"},
  {"seq":16,"type":"arena_alloc","arena":"spells","offset":40,"pad":0,"size":40,"align":8,"top":80,"kind":"Spell","label":"Meteor"},
  {"seq":17,"type":"log","text":"Casting Meteor"},
  {"seq":18,"type":"arena_alloc","arena":"spells","offset":80,"pad":0,"size":40,"align":8,"top":120,"kind":"Spell","label":"Heal"},
  {"seq":19,"type":"log","text":"Casting Heal"},
  {"seq":20,"type":"arena_alloc","arena":"spells","offset":120,"pad":0,"size":40,"align":8,"top":160,"kind":"Spell","label":"Haste"},
  {"seq":21,"type":"log","text":"Casting Haste"},
  {"seq":22,"type":"arena_alloc","arena":"spells","offset":160,"pad":0,"size":40,"align":8,"top":200,"kind":"Spell","label":"Shield"},
  {"seq":23,"type":"log","text":"Casting Shield"},
  {"seq":24,"type":"arena_alloc","arena":"spells","offset":200,"pad":0,"size":40,"align":8,"top":240,"kind":"Spell","label":"Blink"},
  {"seq":25,"type":"log","text":"Casting Blink"},
  {"seq":26,"type":"arena_oom","arena":"spells","offset":240,"size":40,"pad":0,"kind":"Spell"},
  {"seq":27,"type":"log","text":"Out of spell memory, Nova fizzles"},
  {"seq":28,"type":"arena_reset_begin","arena":"spells","objects":6},
  {"seq":29,"type":"arena_reset","arena":"spells"},
  {"seq":30,"type":"section","title":"Pool","text":"Six fixed-size Monster slots. Freed slots go on a stack and are reused first."},
  {"seq":31,"type":"pool_create","pool":"monsters","slots":6,"slot_size":40,"kind":"Monster","free":[0,1,2,3,4,5]},
  {"seq":32,"type":"log","text":"Monster spawned: Goblin"},
  {"seq":33,"type":"monster_new","label":"Goblin","hp":30},
  {"seq":34,"type":"pool_alloc","pool":"monsters","slot":0,"offset":0,"label":"Goblin","free":[1,2,3,4,5]},
  {"seq":35,"type":"log","text":"Monster spawned: Orc"},
  {"seq":36,"type":"monster_new","label":"Orc","hp":60},
  {"seq":37,"type":"pool_alloc","pool":"monsters","slot":1,"offset":40,"label":"Orc","free":[2,3,4,5]},
  {"seq":38,"type":"log","text":"Monster spawned: Slime"},
  {"seq":39,"type":"monster_new","label":"Slime","hp":20},
  {"seq":40,"type":"pool_alloc","pool":"monsters","slot":2,"offset":80,"label":"Slime","free":[3,4,5]},
  {"seq":41,"type":"log","text":"Monster spawned: Bat"},
  {"seq":42,"type":"monster_new","label":"Bat","hp":10},
  {"seq":43,"type":"pool_alloc","pool":"monsters","slot":3,"offset":120,"label":"Bat","free":[4,5]},
  {"seq":44,"type":"log","text":"Goblin attacks!"},
  {"seq":45,"type":"log","text":"Orc attacks!"},
  {"seq":46,"type":"note","text":"The hero fights the Goblin. When it dies its slot is pushed onto the free stack."},
  {"seq":47,"type":"log","text":"Goblin takes 18 damage (12 hp left)"},
  {"seq":48,"type":"monster_hit","label":"Goblin","damage":18,"hp":12},
  {"seq":49,"type":"log","text":"Goblin takes 15 damage (0 hp left)"},
  {"seq":50,"type":"monster_hit","label":"Goblin","damage":15,"hp":0},
  {"seq":51,"type":"log","text":"Monster destroyed: Goblin"},
  {"seq":52,"type":"monster_destroyed","label":"Goblin"},
  {"seq":53,"type":"pool_free","pool":"monsters","slot":0,"offset":0,"label":"Goblin","free":[0,4,5]},
  {"seq":54,"type":"note","text":"A Troll spawns and gets the Goblin's old slot: last freed, first reused."},
  {"seq":55,"type":"log","text":"Monster spawned: Troll"},
  {"seq":56,"type":"monster_new","label":"Troll","hp":120},
  {"seq":57,"type":"pool_alloc","pool":"monsters","slot":0,"offset":0,"label":"Troll","free":[4,5]},
  {"seq":58,"type":"log","text":"Troll attacks!"},
  {"seq":59,"type":"log","text":"Bat takes 12 damage (0 hp left)"},
  {"seq":60,"type":"monster_hit","label":"Bat","damage":12,"hp":0},
  {"seq":61,"type":"log","text":"Monster destroyed: Bat"},
  {"seq":62,"type":"monster_destroyed","label":"Bat"},
  {"seq":63,"type":"pool_free","pool":"monsters","slot":3,"offset":120,"label":"Bat","free":[3,4,5]},
  {"seq":64,"type":"log","text":"Slime takes 25 damage (0 hp left)"},
  {"seq":65,"type":"monster_hit","label":"Slime","damage":25,"hp":0},
  {"seq":66,"type":"log","text":"Monster destroyed: Slime"},
  {"seq":67,"type":"monster_destroyed","label":"Slime"},
  {"seq":68,"type":"pool_free","pool":"monsters","slot":2,"offset":80,"label":"Slime","free":[2,3,4,5]},
  {"seq":69,"type":"note","text":"A Wolf spawns into the Slime's slot. The old slime pointer still points there..."},
  {"seq":70,"type":"log","text":"Monster spawned: Wolf"},
  {"seq":71,"type":"monster_new","label":"Wolf","hp":40},
  {"seq":72,"type":"pool_alloc","pool":"monsters","slot":2,"offset":80,"label":"Wolf","free":[3,4,5]},
  {"seq":73,"type":"log","text":"Wolf attacks!"},
  {"seq":74,"type":"note","text":"...so calling through the stale raw pointer silently talks to the Wolf. A pool cannot catch this."},
  {"seq":75,"type":"raw_alias","pool":"monsters","name":"slime","slot":2,"expected":"Slime","actual":"Wolf"},
  {"seq":76,"type":"log","text":"Wolf attacks!"},
  {"seq":77,"type":"note","text":"Destroying the Bat twice would corrupt the free list. The pool checks its live flags and refuses."},
  {"seq":78,"type":"pool_double_free","pool":"monsters","slot":3,"offset":120,"label":"","free":[3,4,5]},
  {"seq":79,"type":"note","text":"Fill the remaining slots. The seventh monster has nowhere to go."},
  {"seq":80,"type":"log","text":"Monster spawned: Imp"},
  {"seq":81,"type":"monster_new","label":"Imp","hp":15},
  {"seq":82,"type":"pool_alloc","pool":"monsters","slot":3,"offset":120,"label":"Imp","free":[4,5]},
  {"seq":83,"type":"log","text":"Monster spawned: Ghoul"},
  {"seq":84,"type":"monster_new","label":"Ghoul","hp":45},
  {"seq":85,"type":"pool_alloc","pool":"monsters","slot":4,"offset":160,"label":"Ghoul","free":[5]},
  {"seq":86,"type":"log","text":"Monster spawned: Wraith"},
  {"seq":87,"type":"monster_new","label":"Wraith","hp":50},
  {"seq":88,"type":"pool_alloc","pool":"monsters","slot":5,"offset":200,"label":"Wraith","free":[]},
  {"seq":89,"type":"pool_full","pool":"monsters"},
  {"seq":90,"type":"log","text":"Pool full, the Hydra cannot spawn"},
  {"seq":91,"type":"note","text":"Pool goes out of scope: every live slot is destroyed."},
  {"seq":92,"type":"log","text":"Monster destroyed: Troll"},
  {"seq":93,"type":"monster_destroyed","label":"Troll"},
  {"seq":94,"type":"pool_free","pool":"monsters","slot":0,"offset":0,"label":"Troll","free":[0]},
  {"seq":95,"type":"log","text":"Monster destroyed: Orc"},
  {"seq":96,"type":"monster_destroyed","label":"Orc"},
  {"seq":97,"type":"pool_free","pool":"monsters","slot":1,"offset":40,"label":"Orc","free":[1,0]},
  {"seq":98,"type":"log","text":"Monster destroyed: Wolf"},
  {"seq":99,"type":"monster_destroyed","label":"Wolf"},
  {"seq":100,"type":"pool_free","pool":"monsters","slot":2,"offset":80,"label":"Wolf","free":[2,1,0]},
  {"seq":101,"type":"log","text":"Monster destroyed: Imp"},
  {"seq":102,"type":"monster_destroyed","label":"Imp"},
  {"seq":103,"type":"pool_free","pool":"monsters","slot":3,"offset":120,"label":"Imp","free":[3,2,1,0]},
  {"seq":104,"type":"log","text":"Monster destroyed: Ghoul"},
  {"seq":105,"type":"monster_destroyed","label":"Ghoul"},
  {"seq":106,"type":"pool_free","pool":"monsters","slot":4,"offset":160,"label":"Ghoul","free":[4,3,2,1,0]},
  {"seq":107,"type":"log","text":"Monster destroyed: Wraith"},
  {"seq":108,"type":"monster_destroyed","label":"Wraith"},
  {"seq":109,"type":"pool_free","pool":"monsters","slot":5,"offset":200,"label":"Wraith","free":[5,4,3,2,1,0]},
  {"seq":110,"type":"section","title":"World","text":"Arena-backed objects behind reference-counted, generation-checked world_ptr handles."},
  {"seq":111,"type":"arena_create","arena":"world","cap":1024},
  {"seq":112,"type":"log","text":"Monster spawned: Minotaur"},
  {"seq":113,"type":"monster_new","label":"Minotaur","hp":80},
  {"seq":114,"type":"arena_alloc","arena":"world","offset":0,"pad":0,"size":40,"align":8,"top":40,"kind":"Monster","label":"Minotaur"},
  {"seq":115,"type":"world_spawn","slot":0,"gen":1,"offset":0,"size":40,"label":"Minotaur"},
  {"seq":116,"type":"handle_new","handle":1,"slot":0,"gen":1,"slot_gen":1,"refs":1,"valid":true},
  {"seq":117,"type":"log","text":"Minotaur attacks!"},
  {"seq":118,"type":"note","text":"Copying a handle bumps the record's refcount; the copy dies at the end of the scope."},
  {"seq":119,"type":"handle_copy","handle":2,"slot":0,"gen":1,"slot_gen":1,"refs":2,"valid":true,"from":1},
  {"seq":120,"type":"log","text":"Minotaur attacks!"},
  {"seq":121,"type":"handle_drop","handle":2,"slot":0,"gen":1,"slot_gen":1,"refs":1,"valid":true},
  {"seq":122,"type":"log","text":"Monster spawned: Dragon"},
  {"seq":123,"type":"monster_new","label":"Dragon","hp":200},
  {"seq":124,"type":"arena_alloc","arena":"world","offset":40,"pad":0,"size":40,"align":8,"top":80,"kind":"Monster","label":"Dragon"},
  {"seq":125,"type":"world_spawn","slot":1,"gen":1,"offset":40,"size":40,"label":"Dragon"},
  {"seq":126,"type":"handle_new","handle":3,"slot":1,"gen":1,"slot_gen":1,"refs":1,"valid":true},
  {"seq":127,"type":"log","text":"Monster spawned: Skeleton"},
  {"seq":128,"type":"monster_new","label":"Skeleton","hp":25},
  {"seq":129,"type":"arena_alloc","arena":"world","offset":80,"pad":0,"size":40,"align":8,"top":120,"kind":"Monster","label":"Skeleton"},
  {"seq":130,"type":"world_spawn","slot":2,"gen":1,"offset":80,"size":40,"label":"Skeleton"},
  {"seq":131,"type":"handle_new","handle":4,"slot":2,"gen":1,"slot_gen":1,"refs":1,"valid":true},
  {"seq":132,"type":"log","text":"Skeleton attacks!"},
  {"seq":133,"type":"handle_drop","handle":4,"slot":2,"gen":1,"slot_gen":1,"refs":0,"valid":true},
  {"seq":134,"type":"note","text":"The Skeleton has no handles left, but it stays alive until collect() runs."},
  {"seq":135,"type":"world_collect_begin"},
  {"seq":136,"type":"log","text":"Monster destroyed: Skeleton"},
  {"seq":137,"type":"monster_destroyed","label":"Skeleton"},
  {"seq":138,"type":"arena_release","arena":"world","offset":80},
  {"seq":139,"type":"world_release","slot":2,"gen":2,"offset":80,"reason":"collect"},
  {"seq":140,"type":"world_collect_end","arena_used":120},
  {"seq":141,"type":"note","text":"collect() destroyed it and bumped its slot generation. Its arena bytes stay as a hole until reset."},
  {"seq":142,"type":"log","text":"Monster spawned: Lich"},
  {"seq":143,"type":"monster_new","label":"Lich","hp":90},
  {"seq":144,"type":"arena_alloc","arena":"world","offset":120,"pad":0,"size":40,"align":8,"top":160,"kind":"Monster","label":"Lich"},
  {"seq":145,"type":"world_spawn","slot":2,"gen":2,"offset":120,"size":40,"label":"Lich"},
  {"seq":146,"type":"handle_new","handle":5,"slot":2,"gen":2,"slot_gen":2,"refs":1,"valid":true},
  {"seq":147,"type":"note","text":"The Lich reuses the Skeleton's record slot (generation 2) but takes fresh arena bytes at the top."},
  {"seq":148,"type":"note","text":"Keep a second handle to the Dragon, then kill it outright while that handle still exists."},
  {"seq":149,"type":"handle_copy","handle":6,"slot":1,"gen":1,"slot_gen":1,"refs":2,"valid":true,"from":3},
  {"seq":150,"type":"log","text":"Dragon takes 120 damage (80 hp left)"},
  {"seq":151,"type":"monster_hit","label":"Dragon","damage":120,"hp":80},
  {"seq":152,"type":"log","text":"Dragon takes 90 damage (0 hp left)"},
  {"seq":153,"type":"monster_hit","label":"Dragon","damage":90,"hp":0},
  {"seq":154,"type":"log","text":"Monster destroyed: Dragon"},
  {"seq":155,"type":"monster_destroyed","label":"Dragon"},
  {"seq":156,"type":"arena_release","arena":"world","offset":40},
  {"seq":157,"type":"world_release","slot":1,"gen":2,"offset":40,"reason":"kill"},
  {"seq":158,"type":"note","text":"The old handle remembers generation 1, the slot is now at 2: dereferencing it is caught."},
  {"seq":159,"type":"stale_access","handle":6,"slot":1,"gen":1,"slot_gen":2,"refs":0,"valid":false},
  {"seq":160,"type":"log","text":"Caught: dereferenced a world_ptr whose object is gone"},
  {"seq":161,"type":"log","text":"Monster spawned: Wyvern"},
  {"seq":162,"type":"monster_new","label":"Wyvern","hp":70},
  {"seq":163,"type":"arena_alloc","arena":"world","offset":160,"pad":0,"size":40,"align":8,"top":200,"kind":"Monster","label":"Wyvern"},
  {"seq":164,"type":"world_spawn","slot":1,"gen":2,"offset":160,"size":40,"label":"Wyvern"},
  {"seq":165,"type":"handle_new","handle":7,"slot":1,"gen":2,"slot_gen":2,"refs":1,"valid":true},
  {"seq":166,"type":"note","text":"A Wyvern moves into the Dragon's old slot. The stale handle is still rejected: generations differ."},
  {"seq":167,"type":"log","text":"remembered dragon handle is stale, Wyvern is safe"},
  {"seq":168,"type":"log","text":"Wyvern attacks!"},
  {"seq":169,"type":"log","text":"Lich attacks!"},
  {"seq":170,"type":"note","text":"End of scope: handles drop, then the World resets its arena and destroys what is left."},
  {"seq":171,"type":"handle_drop","handle":7,"slot":1,"gen":2,"slot_gen":2,"refs":0,"valid":true},
  {"seq":172,"type":"handle_drop","handle":6,"slot":1,"gen":1,"slot_gen":2,"refs":0,"valid":false},
  {"seq":173,"type":"handle_drop","handle":5,"slot":2,"gen":2,"slot_gen":2,"refs":0,"valid":true},
  {"seq":174,"type":"handle_drop","handle":3,"slot":1,"gen":1,"slot_gen":2,"refs":0,"valid":false},
  {"seq":175,"type":"handle_drop","handle":1,"slot":0,"gen":1,"slot_gen":1,"refs":0,"valid":true},
  {"seq":176,"type":"arena_reset_begin","arena":"world","objects":3},
  {"seq":177,"type":"log","text":"Monster destroyed: Wyvern"},
  {"seq":178,"type":"monster_destroyed","label":"Wyvern"},
  {"seq":179,"type":"log","text":"Monster destroyed: Lich"},
  {"seq":180,"type":"monster_destroyed","label":"Lich"},
  {"seq":181,"type":"log","text":"Monster destroyed: Minotaur"},
  {"seq":182,"type":"monster_destroyed","label":"Minotaur"},
  {"seq":183,"type":"arena_reset","arena":"world"}
]};
